//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlaughterHouseClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_slip_item
    {
        public string product_slip_no { get; set; }
        public string product_code { get; set; }
        public int location_code { get; set; }
        public string lot_no { get; set; }
        public int seq { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<decimal> wgh { get; set; }
        public System.DateTime create_at { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> modified_at { get; set; }
        public string modified_by { get; set; }
    
        public virtual location location { get; set; }
        public virtual product_slip product_slip { get; set; }
        public virtual product product { get; set; }
    }
}
