//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlaughterHouseClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class production_order_item
    {
        public string po_no { get; set; }
        public string product_code { get; set; }
        public int seq { get; set; }
        public int po_qty { get; set; }
        public decimal po_wgh { get; set; }
        public int unload_qty { get; set; }
        public decimal unload_wgh { get; set; }
        public System.DateTime create_at { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> modified_at { get; set; }
        public string modified_by { get; set; }
    
        public virtual production_order production_order { get; set; }
        public virtual product product { get; set; }
    }
}
