//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlaughterHouseClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class receive
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public receive()
        {
            this.receive_item = new HashSet<receive_item>();
        }
    
        public string receive_no { get; set; }
        public System.DateTime receive_date { get; set; }
        public string transport_doc_no { get; set; }
        public string truck_no { get; set; }
        public string farm_code { get; set; }
        public string coop_no { get; set; }
        public int breeder_code { get; set; }
        public int queue_no { get; set; }
        public string lot_no { get; set; }
        public int farm_qty { get; set; }
        public decimal farm_wgh { get; set; }
        public int factory_qty { get; set; }
        public decimal factory_wgh { get; set; }
        public int receive_flag { get; set; }
        public System.DateTime create_at { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> modified_at { get; set; }
        public string modified_by { get; set; }
    
        public virtual breeder breeder { get; set; }
        public virtual farm farm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<receive_item> receive_item { get; set; }
    }
}
