//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlaughterHouseClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class receive_item_by_product
    {
        public string receive_no { get; set; }
        public string bom_product_code { get; set; }
        public string product_code { get; set; }
        public string lot_no { get; set; }
        public int target_qty { get; set; }
        public decimal target_wgh { get; set; }
        public int actual_qty { get; set; }
        public decimal actual_wgh { get; set; }
        public System.DateTime create_at { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> modified_at { get; set; }
        public string modified_by { get; set; }
    
        public virtual product product { get; set; }
    }
}
