//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlaughterHouseClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class unit_of_measurement
    {
        public unit_of_measurement()
        {
            this.products = new HashSet<product>();
            this.products1 = new HashSet<product>();
        }
    
        public int unit_code { get; set; }
        public string unit_name { get; set; }
        public bool active { get; set; }
        public System.DateTime create_at { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> modified_at { get; set; }
        public string modified_by { get; set; }
    
        public virtual ICollection<product> products { get; set; }
        public virtual ICollection<product> products1 { get; set; }
    }
}
